[project]
name = "PlayerCounter"
namespace = "Examples.PlayerCounter"

[compilation]
optimize_for_performance = true
generate_debug_info = true
target_udonsharp_version = "1.1"


[compilation.dev]
include_debug_comments = true
wasm_opt_level = 1
generate_test_helpers = true

[compilation.release]
optimize_for_performance = true
generate_debug_info = false
wasm_opt_level = 3
strip_debug_symbols = true